[package]
name = "theisland"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
dashmap = "6.1.0"
image = "0.25.8"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.48.0", features = ["full"] }
uuid = { version = "1.18.1", features = ["v4", "serde"] }
